### ISSUE TITLE
neovim telescope translate error ..

### ISSUE THREAD

**Issue by xaotag** [Mofiqul/dracula.nvim#32]
![image](https://user-images.githubusercontent.com/40427877/153389326-563fb2dc-225a-4e63-a519-a1778eca994f.png)

**Comment by binhtran432k** [comment]
I also have this problem with whichkey. I just took a look at the file init.lua and see this: https://github.com/Mofiqul/dracula.nvim/blob/a219971291c56bcca3827cb7bd40aaaef23feeca/lua/dracula/init.lua#L75-L80
This may be because telescope, whichkey is floating window. I think author should add configuration to transparent list of color for more situation like instead of hard configuration.
